"""allow null episode duration

Revision ID: 029b9c56b47a
Revises: 
Create Date: 2026-09-05 11:17:43.142572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029b9c56b47a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episodes', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
